// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBO6UPgAj_fAv8aHjp3iB7EfQS4y8i2ac',
    appId: '1:121634292544:web:bc88dc50a70f9beb6a70a5',
    messagingSenderId: '121634292544',
    projectId: 'acadmy-dfc81',
    authDomain: 'acadmy-dfc81.firebaseapp.com',
    storageBucket: 'acadmy-dfc81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXdpfxURJLaS45ikZwBXGp2MPDLGu-SyI',
    appId: '1:121634292544:android:dea3e0ba23a66cf76a70a5',
    messagingSenderId: '121634292544',
    projectId: 'acadmy-dfc81',
    storageBucket: 'acadmy-dfc81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQt68W7mKjppwcnT8ItknKtlMyE53EE_Q',
    appId: '1:121634292544:ios:39be81ddd5e710196a70a5',
    messagingSenderId: '121634292544',
    projectId: 'acadmy-dfc81',
    storageBucket: 'acadmy-dfc81.appspot.com',
    iosClientId: '121634292544-8khrlafkrs72ph02ldojdu61i91hvtjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.acadmyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQt68W7mKjppwcnT8ItknKtlMyE53EE_Q',
    appId: '1:121634292544:ios:39be81ddd5e710196a70a5',
    messagingSenderId: '121634292544',
    projectId: 'acadmy-dfc81',
    storageBucket: 'acadmy-dfc81.appspot.com',
    iosClientId: '121634292544-8khrlafkrs72ph02ldojdu61i91hvtjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.acadmyApp',
  );
}
